### ISSUE TITLE
Add Botton to the left of Tags

### ISSUE THREAD

**Issue by CreativeCodeCat** [The-Repo-Club/instawm#4]
@XDream8 hey mate when you get time can you have a look at adding this patch to the code and doing a PR please.

[statusbutton.diff](https://dwm.suckless.org/patches/statusbutton/dwm-statusbutton-20180524-c8e9479.diff)

**Comment by XDream8** [comment]
I will take a look at it later today.

**Comment by CreativeCodeCat** [comment]
Cheers mate :) I'll give it a test and merge :)

**Comment by XDream8** [comment]
I will fork dwl and work on it to see if i can add the things i need and use it on daily basis when i have some time.

**Comment by CreativeCodeCat** [comment]
if you do please do let me know and ill check it out and maybe switch to wayland myself.
